[workspace]
resolver = "2"
members = ["passkey-wallet"]

[workspace.dependencies]
soroban-sdk = "26.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.test-optimized]
inherits = "release"
opt-level = 1
debug = true
strip = "none"
