'use client'

import { useEffect, useRef } from 'react'

const DIAGRAMS: Record<string, string> = {
  registration: `sequenceDiagram
    participant U as User
    participant App as dApp / Wallet UI
    participant A as Device Authenticator<br/>(Secure Enclave / TPM)
    participant S as Stellar Network<br/>(Soroban)

    U->>App: "Create wallet"
    App->>A: navigator.credentials.create()<br/>(WebAuthn registration ceremony)
    A->>U: Biometric prompt (Face ID / Touch ID / PIN)
    U->>A: Approve
    A-->>App: Credential: { credentialId, P-256 public key }
    Note over A: Private key never leaves<br/>the secure enclave
    App->>S: Deploy smart account contract<br/>with public key as signer<br/>(fee-sponsored deployment)
    S-->>App: contractId (the wallet address)
    App->>App: Persist { contractId, credentialId }`,

  signing: `sequenceDiagram
    participant U as User
    participant App as dApp / Wallet UI
    participant A as Device Authenticator
    participant S as Stellar Network<br/>(Soroban)

    App->>App: Build Soroban transaction<br/>(e.g. token transfer from contractId)
    App->>App: Compute signature payload hash<br/>(the WebAuthn challenge)
    App->>A: navigator.credentials.get()<br/>(challenge = tx hash)
    A->>U: Biometric prompt
    U->>A: Approve
    A-->>App: Assertion: { authenticatorData,<br/>clientDataJSON, signature (DER) }
    App->>App: Normalize signature (DER to raw r,s,<br/>low-S form), build ScVal payload
    App->>S: Submit tx with assertion as<br/>contract auth credentials
    S->>S: Verifier contract checks secp256r1<br/>signature against stored public key
    S-->>App: Transaction result`,

  recovery: `flowchart LR
    A[All passkey<br/>devices lost] --> B[Sign 'add new signer' tx<br/>with backup Ed25519 key]
    B --> C[Contract adds new<br/>passkey public key]
    C --> D[User signs with<br/>new device passkey]`,

  fallback: `flowchart TD
    A{Platform authenticator<br/>available?} -->|Yes| B[Synced platform passkey<br/>Face ID / Touch ID / Windows Hello]
    A -->|No| C{Hardware key<br/>available?}
    C -->|Yes| D[FIDO2 security key<br/>YubiKey, Titan]
    C -->|No| E[Ed25519 backup keypair<br/>classic flow]
    B -.recovery.-> E
    D -.recovery.-> E`,

  sdk: `flowchart TB
    subgraph dapps ["dApps and Wallets"]
        DAPP["Any Stellar dApp"]
        DEMO["demo app"]
    end

    subgraph kit ["@creit-tech/stellar-wallets-kit"]
        ADAPTER["wallets-kit-adapter<br/>getAddress() / signTransaction() / isAvailable()"]
        OTHERS["Freighter / Lobstr / xBull modules"]
    end

    subgraph ours ["This project"]
        UI["passkey-ui<br/>pk-create / pk-sign-tx / pk-recover<br/>(headless Web Components)"]
        SDK["passkey-sdk<br/>WebAuthn ceremony / encoding normalization<br/>Soroban signature payload construction"]
    end

    subgraph platform ["Platform"]
        WEBAUTHN["@simplewebauthn/browser<br/>(WebAuthn API)"]
        OZ["OpenZeppelin verifier contracts<br/>(deployed on Stellar)"]
    end

    DAPP --> ADAPTER
    DAPP --> UI
    DEMO --> ADAPTER
    ADAPTER --> SDK
    UI --> SDK
    SDK --> WEBAUTHN
    SDK -->|"formats payloads for"| OZ`,
}

const ARCH_HTML = `
<h1>Architecture: Passkeys on Stellar</h1>
<p>How passkey-secured smart accounts work on Stellar, the design considerations driving our choices, and the architecture and requirements for the SDK we are building.</p>

<h2>1. How Passkeys Work on Stellar</h2>

<h3>The Core Idea</h3>
<p>On Stellar, a passkey wallet is <strong>a Soroban smart contract, not a keypair</strong>. The contract holds a list of authorized signers; one of them is a P-256 (secp256r1) public key generated by the user's device authenticator. Protocol 21 (CAP-0051) added native secp256r1 verification inside Soroban, so the passkey assertion is verified on-chain with no bridge or intermediary.</p>
<pre><code>User's Wallet = Soroban Smart Contract
  ├── Signer 1: Passkey (P-256 public key from device authenticator)
  ├── Signer 2: Backup Ed25519 keypair (recovery)
  └── Signer N: Additional passkeys, session keys, policies...</code></pre>

<h3>Registration (Wallet Creation)</h3>
<div class="arch-diagram" data-diagram="registration"></div>
<p>Key points:</p>
<ul>
  <li>The <strong>private key never leaves the device</strong>. Only the public key goes on-chain.</li>
  <li>The contract address (<code>contractId</code>) is derived deterministically from the deployer and salt; the app must persist the <code>credentialId → contractId</code> mapping because WebAuthn gives back only the credentialId at sign-in time.</li>
  <li>Deployment fees are paid by a <strong>sponsor account</strong>, so the user starts with zero XLM.</li>
</ul>

<h3>Transaction Signing</h3>
<div class="arch-diagram" data-diagram="signing"></div>
<p>The verification on-chain re-derives what the authenticator signed: <code>sha256(authenticatorData ‖ sha256(clientDataJSON))</code>, where <code>clientDataJSON</code> embeds the challenge (the transaction's signature payload hash). This binds the biometric approval to that exact transaction.</p>

<h3>Recovery</h3>
<p>Passkeys can be lost (device-bound key on a broken laptop, abandoned Apple/Google account). The smart account holds a <strong>backup Ed25519 signer</strong> added at creation time. Recovery is a normal contract invocation signed by the backup key that rotates in a new passkey signer:</p>
<div class="arch-diagram" data-diagram="recovery"></div>

<h2>2. Design Considerations</h2>

<h3>Synced vs. Device-Bound Passkeys</h3>
<p>This single distinction drives most UX and recovery decisions:</p>
<table>
  <thead>
    <tr><th></th><th>Synced passkey</th><th>Device-bound passkey</th></tr>
  </thead>
  <tbody>
    <tr><td><strong>Stored in</strong></td><td>iCloud Keychain / Google Password Manager</td><td>Secure Enclave / TPM / YubiKey</td></tr>
    <tr><td><strong>Survives device loss</strong></td><td>✅ (any device on same account)</td><td>❌ (gone with the device)</td></tr>
    <tr><td><strong>Typical user</strong></td><td>Consumers</td><td>Security keys, enterprise</td></tr>
  </tbody>
</table>
<p>Most consumer passkeys are synced, so the common case is good. But the SDK must treat device-bound credentials as first-class (Firefox, Linux, hardware keys) and always push apps to register a backup signer.</p>

<h3>Platform Fragmentation</h3>
<p>From our compatibility testing on real devices:</p>
<ul>
  <li><strong>Chrome / Safari / Edge</strong> on macOS, iOS, Android, Windows: full support, synced.</li>
  <li><strong>Firefox</strong>: works but credentials are device-local with no sync; conditional UI only on 119+.</li>
  <li><strong>Signature encoding differs</strong>: authenticators return DER-encoded signatures; some produce high-S values that on-chain verifiers reject. The SDK must normalize to raw <code>r‖s</code> low-S form.</li>
  <li><strong><code>credentialId</code> encoding</strong> (base64 vs base64url) differs across libraries and must be normalized at every boundary.</li>
</ul>
<p>Fallback ladder we recommend to integrators:</p>
<div class="arch-diagram" data-diagram="fallback"></div>

<h3>The credentialId → contractId Mapping</h3>
<p>WebAuthn authentication returns only a <code>credentialId</code>. The contract address must be looked up, not derived on the fly, because derivation depends on the deployer key and salt used at creation. Lessons from building this portal:</p>
<ul>
  <li>Persist <code>{ contractId, credentialId }</code> locally at creation time and treat it as the source of truth.</li>
  <li>Always pass both IDs explicitly when connecting; never rely on re-derivation, which silently breaks if the deployer configuration changes.</li>
  <li>For multi-device sign-in (synced passkey, new device), the mapping must come from somewhere durable: an indexer, a registry contract, or a service. This is a core SDK requirement, not an app afterthought.</li>
</ul>

<h3>Fee Sponsorship</h3>
<p>Users start with zero XLM, so both deployment and early transactions need a sponsor:</p>
<ul>
  <li>The sponsor key signs as the <strong>fee source</strong>, while the passkey authorizes the <strong>operation</strong> via contract auth. The two roles must stay decoupled in the SDK API.</li>
  <li>Launchtube and similar services exist for this; the SDK should accept any fee-bump strategy rather than hard-coding one.</li>
</ul>

<h3>Security Posture</h3>
<ul>
  <li>The SDK <strong>does not touch or modify the on-chain verifier contracts</strong> (OpenZeppelin stellar-contracts: deployed, partially audited). It only formats WebAuthn output into the payload the verifier expects, so no new attack surface is introduced at the contract level.</li>
  <li>Passkeys are <strong>origin-bound</strong>: a credential created on one domain cannot be exercised by a phishing site. The flip side: the relying party ID is part of the credential, so domain migrations need explicit planning.</li>
  <li>Challenges must be the actual transaction signature payload hash, never a static or reused value, to prevent replay.</li>
</ul>

<h3>Native Mobile</h3>
<p>Native iOS (<code>ASAuthorizationController</code>) and Android (<code>CredentialManager</code>) produce assertions structurally identical to browser WebAuthn output and work against the same verifier contract. The browser SDK stays web-only; the compatibility docs carry a native bridge section covering formatting differences for React Native, Flutter, Swift, and Kotlin.</p>

<h2>3. SDK Architecture</h2>
<p>The ecosystem has the hard parts solved at the contract level (<a href="https://github.com/OpenZeppelin/stellar-contracts" target="_blank">OpenZeppelin stellar-contracts</a>) and at the full-featured SDK level (<a href="https://github.com/kalepail/smart-account-kit" target="_blank">smart-account-kit</a>). What's missing is the minimal, approachable middle layer. We use smart-account-kit as a <strong>reference implementation</strong>, extracting the minimum viable WebAuthn and Soroban payload logic into a new standalone SDK, and build on the already-deployed OpenZeppelin contracts rather than reinventing the on-chain layer.</p>
<div class="arch-diagram" data-diagram="sdk"></div>

<h3><code>passkey-sdk</code> (core)</h3>
<p>The thin core layer. Wraps <code>@simplewebauthn/browser</code> for registration and authentication, normalizes encoding differences between Chrome, Safari, and Firefox (DER to raw signatures, low-S normalization, base64url credential IDs), and constructs the Soroban <code>ScVal</code> signature payload the verifier contract expects. Narrow API surface:</p>
<pre><code>browserCapabilities()                    // feature-detect before showing passkey UI
createWallet(name)                       // WebAuthn registration + contract deployment
signTransaction(tx, credentialId)        // WebAuthn assertion + payload construction
addBackupSigner(contractId, publicKey)   // register Ed25519 recovery signer
signWithBackup(tx, keypair)              // recovery-path signing</code></pre>

<h3><code>passkey-ui</code> (components)</h3>
<p>Three headless Web Components, one per core flow: <code>&lt;pk-create&gt;</code>, <code>&lt;pk-sign-tx&gt;</code>, <code>&lt;pk-recover&gt;</code>. Each manages the WebAuthn ceremony and emits typed events on completion, with zero opinion on visual styling. For <code>&lt;pk-sign-tx&gt;</code>, the developer owns the transaction summary view (what the user sees before confirming); the component handles only the signing ceremony underneath. A single build works in React, Vue, Svelte, and vanilla JS without adapter shims.</p>

<h3><code>wallets-kit-adapter</code> (connector)</h3>
<p>Implements the <code>IStellarWalletsKit</code> module interface so passkeys appear as a native wallet option alongside Freighter, Lobstr, and xBull. Any dApp already using <a href="https://github.com/Creit-Tech/Stellar-Wallets-Kit" target="_blank">stellar-wallets-kit</a> adds passkey support by registering the adapter; their signing flow doesn't change. Target: a PR into the official repo.</p>

<h3><code>demo</code></h3>
<p>Exercises the full flow end to end through the adapter: create (<code>&lt;pk-create&gt;</code>), sign a Soroban transaction (<code>&lt;pk-sign-tx&gt;</code>), recover via backup key (<code>&lt;pk-recover&gt;</code>). Lives on Testnet.</p>

<h3>Key Technical Decisions</h3>
<table>
  <thead>
    <tr><th>Decision</th><th>Choice</th><th>Reason</th></tr>
  </thead>
  <tbody>
    <tr><td>On-chain contracts</td><td>OpenZeppelin stellar-contracts</td><td>Already deployed, partially audited, modular verifiers</td></tr>
    <tr><td>WebAuthn library</td><td>@simplewebauthn/browser</td><td>Smallest proven abstraction; normalizes browser differences</td></tr>
    <tr><td>UI approach</td><td>Headless Web Components</td><td>Framework-agnostic with one build; developer owns styling</td></tr>
    <tr><td>Test framework</td><td>Vitest</td><td>Fast, native ESM, TypeScript-native</td></tr>
    <tr><td>License</td><td>MIT</td><td>Permissive; compatible with downstream wallet integrations</td></tr>
  </tbody>
</table>

<h2>4. Requirements</h2>

<h3>Functional</h3>
<table>
  <thead>
    <tr><th>#</th><th>Requirement</th></tr>
  </thead>
  <tbody>
    <tr><td>F1</td><td>Create a passkey-secured smart account: WebAuthn registration → contract deployment → return <code>{ contractId, credentialId }</code></td></tr>
    <tr><td>F2</td><td>Sign any Soroban transaction with a passkey assertion bound to that transaction's signature payload hash</td></tr>
    <tr><td>F3</td><td>Register and use an Ed25519 backup signer for recovery when all passkey devices are unavailable</td></tr>
    <tr><td>F4</td><td>Feature-detect capabilities (<code>webauthn</code>, platform authenticator, conditional UI) before any passkey UI is shown</td></tr>
    <tr><td>F5</td><td>Normalize signatures (DER to raw r‖s, low-S) and credential IDs (base64url) across Chrome, Safari, Firefox, and Edge</td></tr>
    <tr><td>F6</td><td>Support fee-sponsored deployment and transactions, with the sponsor strategy pluggable</td></tr>
    <tr><td>F7</td><td>Persist and resolve the <code>credentialId → contractId</code> mapping; never depend on silent re-derivation</td></tr>
    <tr><td>F8</td><td>Implement the full <code>IStellarWalletsKit</code> module interface (<code>getAddress</code>, <code>signTransaction</code>, <code>isAvailable</code>)</td></tr>
    <tr><td>F9</td><td>Ship <code>&lt;pk-create&gt;</code>, <code>&lt;pk-sign-tx&gt;</code>, <code>&lt;pk-recover&gt;</code> as headless Web Components emitting typed events</td></tr>
  </tbody>
</table>

<h3>Non-Functional</h3>
<table>
  <thead>
    <tr><th>#</th><th>Requirement</th></tr>
  </thead>
  <tbody>
    <tr><td>N1</td><td><strong>No contract changes</strong>: only format payloads for the deployed OpenZeppelin verifiers; introduce no new on-chain attack surface</td></tr>
    <tr><td>N2</td><td><strong>Framework-agnostic UI</strong>: one Web Components build usable from React, Vue, Svelte, and vanilla JS</td></tr>
    <tr><td>N3</td><td><strong>Narrow API</strong>: the SDK surface stays small enough to audit in one sitting</td></tr>
    <tr><td>N4</td><td><strong>Documented compatibility</strong>: every supported browser/OS/hardware row in the matrix tested on real devices, with <em>Last tested</em> dates and a quarterly re-test cadence plus per-major-browser-release updates</td></tr>
    <tr><td>N5</td><td><strong>TypeScript-first</strong>: full type coverage, typed component events, Vitest test suite</td></tr>
    <tr><td>N6</td><td><strong>MIT licensed</strong>, published to npm</td></tr>
    <tr><td>N7</td><td><strong>Maintenance</strong>: out-of-cycle update PRs within two weeks of breaking changes in upstream WebAuthn platform APIs or reference contracts; docs ownership transfers to stellar-wallets-kit maintainers once merged there</td></tr>
  </tbody>
</table>
`

export function ArchitectureViewer() {
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      const mermaid = (await import('mermaid')).default
      mermaid.initialize({
        startOnLoad: false,
        theme: 'dark',
        themeVariables: {
          darkMode: true,
          background: '#060d1f',
          primaryColor: '#1e3a8a',
          primaryTextColor: '#ffffff',
          primaryBorderColor: '#3b82f6',
          lineColor: 'rgba(255,255,255,0.5)',
          secondaryColor: '#0a1628',
          tertiaryColor: '#0a1628',
          fontSize: '14px',
        },
      })
      const nodes = ref.current?.querySelectorAll('[data-diagram]') ?? []
      for (const node of Array.from(nodes)) {
        const key = node.getAttribute('data-diagram')
        if (!key || !DIAGRAMS[key]) continue
        try {
          const { svg } = await mermaid.render(`mmd-${key}`, DIAGRAMS[key])
          if (cancelled) return
          node.innerHTML = svg
        } catch {
          // Leave the placeholder empty if a diagram fails to render
        }
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <div
      ref={ref}
      className="rfp-content max-w-none"
      dangerouslySetInnerHTML={{ __html: ARCH_HTML }}
    />
  )
}
